CI pipeline: adapt to bbnavi
- lint & test on any branch & PR
- build & push Docker image only on `release_<bbnavi-config>_<date>[n]` tags
- use Node v10 for now, because haven't merged the upstream `v3` branch yet
- use GitHub Container Registry instead of Gitlab Container Registry
- permanent Docker image tags: remove `v3-` prefix

diff --git a/.github/workflows/lint-test-deploy.yml b/.github/workflows/lint-test-deploy.yml
--- a/.github/workflows/lint-test-deploy.yml
+++ b/.github/workflows/lint-test-deploy.yml
@@ -1,12 +1,14 @@
-name: Process v3 push or PR
+name: lint, test & push Docker image
 
 on:
   push:
     branches:
-      - v3
+      - '*'
+    tags:
+      - 'release_*'
   pull_request:
     branches:
-      - v3
+      - '*'
 
 env:
   # We tell Playwright not to download browser binaries because we use microsoft/playwright-github-action.
@@ -19,7 +21,7 @@ jobs:
     runs-on: ubuntu-latest
     strategy:
       matrix:
-        node-version: [14.x]
+        node-version: [10.x]
     steps:
       - name: Checkout
         uses: actions/checkout@v2
@@ -61,7 +63,7 @@ jobs:
     runs-on: ubuntu-latest
     strategy:
       matrix:
-        node-version: [14.x]
+        node-version: [10.x]
     steps:
       - name: Checkout
         uses: actions/checkout@v2
@@ -114,7 +116,7 @@ jobs:
     runs-on: ubuntu-latest
     strategy:
       matrix:
-        node-version: [14.x]
+        node-version: [10.x]
     steps:
       - name: Checkout
         uses: actions/checkout@v2
@@ -172,7 +174,7 @@ jobs:
     runs-on: ubuntu-latest
     strategy:
       matrix:
-        node-version: [14.x]
+        node-version: [10.x]
     steps:
       - name: Checkout
         uses: actions/checkout@v2
@@ -235,7 +237,7 @@ jobs:
         run: yarn run test-report
 
   docker-push:
-    if: github.ref == 'refs/heads/v3'
+    if: github.ref_type == 'tag' && startsWith(github.ref_name, 'release_')
     needs:
       - lint
       - unit-test
@@ -254,23 +256,39 @@ jobs:
       - name: Configure Docker Buildx
         uses: docker/setup-buildx-action@v1
 
-      - name: Log in to DockerHub
+      - name: log into GitHub Container Registry
         uses: docker/login-action@v1 
         with:
-          username: ${{ secrets.DOCKER_USER }}
-          password: ${{ secrets.DOCKER_AUTH }}
+          registry: ghcr.io
+          username: ${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: compute Docker image tag
-        id: docker-tags
+      - name: parse name of bbnavi config from Git tag
+        id: bbnavi-config
+        # Strip "release_" prefix & date suffix from Git tag, set as output.
+        # With an invalid tag (e.g. `release_foo_bar`), this fails.
         run: |
-          echo "permanent-tag=v3-$(date +"%Y-%m-%dT%H.%M.%S")-${GITHUB_SHA:0:7}" >>$GITHUB_OUTPUT
+          set -e -u -o pipefail # fail on errors
+          sudo apt install --no-install-recommends -qq -y pcre2-utils
+          set -x
+          cfg="$(echo -n "${{ github.ref_name }}" | pcre2grep -o1 '(?:release_)([\w-]+)(?:_\d{4}-\d{2}-\d{2})')"
+          echo "cfg=\"$cfg\"" >>$GITHUB_OUTPUT
+
+      - name: compute Docker image metadata
+        id: docker-meta
+        run: |
+          set -e -x -u -o pipefail # fail on errors
+          echo "image=ghcr.io/${{ github.repository }}" >>$GITHUB_OUTPUT
+          echo "permanent-tag=$(date +"%Y-%m-%dT%H.%M.%S")-${GITHUB_SHA:0:7}" >>$GITHUB_OUTPUT
+          echo "release-tag=${{ github.ref_name }}" >>$GITHUB_OUTPUT
+
       - name: build and push Docker image
         uses: docker/build-push-action@v2
         with:
           context: .
           tags: |
-            hsldevcom/digitransit-ui:v3
-            hsldevcom/digitransit-ui:${{ steps.docker-tags.outputs.permanent-tag }}
+            ${{ steps.docker-meta.outputs.image }}:${{ steps.docker-meta.outputs.permanent-tag }}
+            ${{ steps.docker-meta.outputs.image }}:${{ steps.docker-meta.outputs.release-tag }}
           # https://github.com/docker/build-push-action/blob/9472e9021074a3cb3279ba431598b8836d40433f/docs/advanced/cache.md#github-cache
           # https://github.com/moby/buildkit#registry-push-image-and-cache-separately
           cache-from: type=gha
